;;; noita.el --- Lift keystrokes as functors -*- lexical-binding: t -*-

;; Author: gynamics
;; Maintainer: gynamics
;; Version: 0.1
;; Package-Requires: ((emacs "29.1"))
;; Homepage: https://github.com/gynamics/noita.el
;; Keywords: convenience


;; This file is not part of GNU Emacs

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.


;;; Commentary:

;; Note that text edit by macros is such a structure:
;;
;; 1. Text is a finite sequence of symbols.
;; 2. Each text edit is an endomorphism defined on set of text.
;; 3. For each text there is a morphism from text to a buffer in Emacs.
;; 4. For each edit there is a morphism from a Elisp command to this edit
;; 5. For each Elisp command in Emacs there is a morphism from a key sequence in
;; Emacs to this command.
;; 6. There is a natural morphism from key sequences to text.
;;
;; Note that if we introduce a morphism from text to key sequences, then:
;;
;; 1. Endomorphism: edit(text)
;; 2. Morphism: text -> key sequences -> Elisp command -> edit
;; 3. Morphism: key sequences -> text -> buffer
;;
;; Duality: edit(text) -> text(edit)
;;
;; Noita constructs the functor category text(edit) recursively.  The noita
;; control buffer can be thought as an environment for writing temporary macros.
;;
;; This implementation trys to maintain things buffer-local.  It is a relatively
;; clear and safe, but it lacks of identical features of kmacro if you want to
;; record cross-buffer events.  Besides we don't use minibuffer hooks, because
;; callbacks can't determine the identity of noita buffers.  Related work may be
;; added later with the integration of `oboe', but I don't want to do it now.


;;; Code:

(defgroup noita nil
  "Lift keystrokes as functors."
  :group 'convenience)

(defcustom noita-new-buffer
  (lambda (ibuf)
    (get-buffer-create (format "*Noita -> %s*" (buffer-name ibuf))))
  "Make a new buffer for noita control."
  :type 'function
  :group 'noita)

(defun noita--local-value (var &optional buf)
  "Return buffer-local value of VAR in BUF, if VAR is void, return nil.
If BUF is omitted, use current buffer."
  (condition-case nil
      (buffer-local-value var (or buf (current-buffer)))
    (void-variable nil)))

;; FR: Implement one-to-many and many-to-one
;; This require us to be able to identify noita buffers globally
;; consider integration `oboe' buffer management framework.

(defun noita--assoc-buf (abuf buf)
  "Find a live locally bound ABUF in BUF."
  (let ((a (noita--local-value abuf buf)))
    (when (buffer-live-p a) a)))

(defun noita--assoc-cbuf (&optional buf)
  "Find associated control buffer of BUF.
If it does not exist return nil."
  (noita--assoc-buf 'noita--control-buffer buf))

(defun noita--assoc-ibuf (&optional buf)
  "Find associated image buffer of BUF.
If it does not exist return nil."
  (noita--assoc-buf 'noita--image-buffer buf))

(defmacro noita--detect-assoc-bufs (buf &rest body)
  "Detect associated buffers in buffer BUF.
Bound them to lexical variables cbuf and ibuf, then execute BODY."
  `(let ((buf ,buf))
     (let ((cbuf (noita--assoc-cbuf buf))
           (ibuf (noita--assoc-ibuf buf)))
       ,@body)))

;;;###autoload
(defun noita ()
  "Lift key inputs in current buffer as functors."
  (interactive)
  (let* ((ibuf (current-buffer))
         (cbuf (or (noita--assoc-cbuf ibuf)
                   (funcall noita-new-buffer ibuf))))
    (with-current-buffer ibuf
      (noita-minor-mode)
      (setq-local noita--control-buffer cbuf))
    (with-current-buffer cbuf
      (noita-mode)
      (setq-local noita--image-buffer ibuf))
    (display-buffer cbuf)))

(defun noita-switch-ibuf ()
  "Switch to its noita control buffer if it exists."
  (interactive)
  (when-let* ((ibuf (noita--assoc-ibuf)))
    (switch-to-buffer-other-window ibuf)))

(defun noita-switch-cbuf ()
  "Switch to its noita control buffer if it exists."
  (interactive)
  (when-let* ((cbuf (noita--assoc-cbuf)))
    (switch-to-buffer-other-window cbuf)))

(defun noita-dye (s)
  "Dye string S according to its hash value."
  ;; This color palette is generated by my perfect palette algorithm, with
  ;; arguments (8 3 (/ float-pi 4) (/ float-pi 6))
  (let* ((colors '("#f9d9b9" "#b9f9e9" "#f9b9f9" "#e9f9b9" "#b9d9f9" "#f9b9c9" "#b9f9b9" "#c9b9f9"))
         (n (mod (sxhash s) (length colors))))
    (propertize s 'face `(:foreground ,(nth n colors) :extend nil))))

(defun noita-paint-key (s buf)
  "Paint key string S in control buffer BUF."
  (with-current-buffer buf
    (save-excursion
      (goto-char (point-max))
      ;; FR: implement a customizable indent function
      (unless (= (line-beginning-position) (point))
        (insert " "))
      (insert (noita-dye s)))))

(defcustom noita-ignore-cmds
  '(noita-bypass-lift-key noita-switch-ibuf noita-switch-cbuf kill-buffer)
  "List of commands that ignored by noita."
  :type '(list command)
  :group 'noita)

(defcustom noita-ignore-keys '()
  "List of keys that ignored by noita."
  :type '(list string)
  :group 'noita)

(defun noita-lift-key-pre ()
  "Cache key information before command is running."
  (unless (noita--local-value 'noita--bypass-lift-key)
    (setq-local noita--prefix-keys (key-description (this-command-keys)))))

(defun noita-lift-key ()
  "Record keys to noita control buffer."
  (unless (noita--local-value 'noita--bypass-lift-key)
    (when-let* ((cbuf (noita--assoc-cbuf))
               (cmd this-command)
               (keys (this-command-keys)))
      (when-let* ((prefix (noita--local-value 'noita--prefix-keys))
                  (s (key-description keys)))
        ;; don't record keys with inconsistent prefix cache
        (if (string-prefix-p prefix s)
            (unless (or (member cmd noita-ignore-cmds)
                        (member s noita-ignore-keys))
              (noita-paint-key s cbuf))
          ;; else
          (setq-local noita--prefix-keys nil))))))

(defun noita-bypass-lift-key ()
  "Toggle whether lifting keys from image buffer."
  (interactive)
  (let ((ibuf (or (noita--assoc-ibuf) (current-buffer)))
        (v (noita--local-value 'noita--bypass-lift-key)))
    (with-current-buffer ibuf
      (setq-local noita--bypass-lift-key (not v)))))

;; FR: Implement a funnel for key compression

(defun noita-revolve (n)
  "Project N th line in noita control buffer."
  (interactive "nProject Line: ")
  (when-let* ((cbuf (noita--assoc-cbuf)))
    (with-current-buffer cbuf
      (let ((m (count-lines (point-min) (point-max))))
        (when (<= 1 n m)
          (save-excursion
            (goto-char (point-min))
            (forward-line (1- n))
            (noita-project)))))))

(defun noita-minor-mode-lighter ()
  "Text for displaying noita minor mode status in modeline."
  (concat
   " "
   (if (noita--local-value 'noita--bypass-lift-key)
       "Noi"
     (propertize "Ita" 'face 'mode-line-highlight))))

(defcustom noita-mode-line '(:eval (noita-minor-mode-lighter))
  "Modeline indicator for `noita-minor-mode'."
  :type 'sexp
  :risky t
  :group 'noita)

(defvar-keymap noita-minor-mode-map
  :doc "Keymap for noita minor mode."
  "C-x C-\\" #'noita-bypass-lift-key
  "C-x <down>" #'noita-switch-cbuf
  "C-c RET" #'noita-revolve)

(defun noita-ibuf-cleanup ()
  "Clean up hooks in noita image buffer."
  (remove-hook 'pre-command-hook #'noita-lift-key-pre)
  (remove-hook 'post-command-hook #'noita-lift-key)
  (remove-hook 'kill-buffer-hook #'noita-ibuf-detach))

(defun noita-ibuf-detach ()
  "When kill noita image buffer, detach it from control buffer."
  (let ((cbuf (noita--assoc-cbuf)))
    (with-current-buffer cbuf
      (noita-cbuf-cleanup))
    (noita-ibuf-cleanup)))

(define-minor-mode noita-minor-mode
  "Minor mode for noita image buffer.

Key bindings:
\\{noita-minor-mode-map\}"
  :lighter noita-mode-line
  :keymap noita-minor-mode-map
  (if noita-minor-mode
      (progn
        (setq-local noita--bypass-lift-key nil
                    noita--prefix-keys nil)
        (add-hook 'pre-command-hook #'noita-lift-key-pre nil t)
        (add-hook 'post-command-hook #'noita-lift-key nil t)
        (add-hook 'kill-buffer-hook #'noita-ibuf-detach nil t))
    (noita-ibuf-cleanup)))

(defun noita-project-str (s)
  "Project keys in string S to image buffer."
  (save-excursion
    (goto-char (point-max))
    (insert "\n")
    (save-window-excursion
      (noita-switch-ibuf)
      (execute-kbd-macro (kbd s)))))

(defun noita--region-or-line ()
  "Return (begin end) list of region if active, otherwise current line."
  (if (region-active-p)
      (list (region-beginning) (region-end))
    (list (line-beginning-position) (line-end-position))))

(defun noita-project ()
  "Project current line to image buffer.
If region is active, project active region."
  (interactive)
  (noita-project-str
   (apply #'buffer-substring-no-properties (noita--region-or-line))))

(defun noita-join-keys (bgn end)
  "Join characters in (BGN END) into one symbol by stripping spaces."
  (interactive "r")
  (when-let* ((s (buffer-substring-no-properties bgn end)))
    (goto-char bgn)
    (kill-region bgn end)
    (insert (concat (split-string s)))))

(defun noita-explode ()
  "Explode symbol at point to a space-separated character sequence string."
  (interactive)
  (when-let* ((bounds (bounds-of-thing-at-point 'symbol))
             (s (buffer-substring-no-properties (car bounds) (cdr bounds))))
    (goto-char (car bounds))
    (kill-region (car bounds) (cdr bounds))
    (insert (mapconcat 'identity (mapcar (lambda (x) (list x)) (string-to-list s)) " "))))

;; FR: should we compute prefix pattern for better fold?
(defun noita--fold-list (l &optional r)
  "Fold repeated elements in list L, store result in R."
  (cond
   ((null l) (nreverse r))
   ((null r) (noita--fold-list (cdr l) (list (cons (car l) 1))))
   (t (noita--fold-list
       (cdr l)
       (if (equal (car l) (caar r))
           (cons (cons (caar r) (1+ (cdar r))) (cdr r))
         (cons (cons (car l) 1) r))))))

(defun noita-fold-keys (bgn end)
  "Fold repeated keys in (BGN END)."
  (interactive (noita--region-or-line))
  (when-let* ((s (buffer-substring-no-properties bgn end)))
    (goto-char bgn)
    (kill-region bgn end)
    (insert
     (mapconcat
      (lambda (c)
        (if (> (cdr c) 4)
            (format "C-u %d %s" (cdr c) (car c))
          (mapconcat #'identity (make-list (cdr c) (car c)) " ")))
      (noita--fold-list (split-string s))
      " "))))

(defun noita-cbuf-cleanup ()
  "Clean up hooks in noita control buffer."
  (remove-hook 'kill-buffer-hook #'noita-cbuf-detach)
  (remove-hook 'change-major-mode-hook #'noita-cbuf-cleanup))

(defun noita-cbuf-detach ()
  "When kill noita control buffer, detach it from image buffer."
  (when-let* ((ibuf (noita--assoc-ibuf)))
    (with-current-buffer ibuf
      (noita-ibuf-cleanup))
    (noita-cbuf-cleanup)))

(define-derived-mode noita-mode ()
  "Noita"
  "Major mode for noita control buffer."
  (keymap-local-set "C-c C-c" #'noita-project)
  (keymap-local-set "C-c e" #'noita-explode)
  (keymap-local-set "C-c f" #'noita-fold-keys)
  (keymap-local-set "C-c j" #'noita-join-keys)
  (keymap-local-set "C-x C-\\" #'noita-bypass-lift-key)
  (keymap-local-set "C-x <up>" #'noita-switch-ibuf)
  (add-hook 'kill-buffer-hook #'noita-cbuf-detach nil t)
  (add-hook 'change-major-mode-hook #'noita-cbuf-cleanup nil t))

(provide 'noita)
;;; noita.el ends here
